# Generated by Django 3.2 on 2023-04-14 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='uped_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.snippet'),
        ),
    ]
