# Generated by Django 3.2 on 2023-04-14 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_alter_fileupload_uped_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='uped_to',
        ),
    ]
