# Generated by Django 3.2 on 2023-04-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_auto_20230418_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='status',
            field=models.CharField(choices=[('案件立ち上げ', '案件立ち上げ'), ('資料受領待ち', '資料受領待ち'), ('積算中', '積算中'), ('施工中', '施工中'), ('設計変更中', '設計変更中'), ('案件完了', '案件完了')], default='案件立ち上げ', max_length=20, verbose_name='進捗状況'),
        ),
    ]
