# Generated by Django 3.2 on 2023-04-19 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0007_snippet_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='date',
        ),
    ]
