# Generated by Django 3.2 on 2023-04-19 06:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0008_remove_snippet_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='duedate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
