# Generated by Django 3.2 on 2023-04-19 06:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0009_snippet_duedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='accept_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='受付日'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='submission_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='提出日'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='duedate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='積算締切日'),
        ),
    ]
