# Generated by Django 3.2 on 2023-04-26 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0012_comment2_fileupload2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='title',
            field=models.CharField(max_length=128, verbose_name='工事件名'),
        ),
    ]
