# Generated by Django 3.2 on 2023-04-02 12:05

from django.db import migrations, models
import snippets.models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_auto_20230402_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='upload',
            field=models.FileField(upload_to=snippets.models.dir_path_name),
        ),
    ]
