# Generated by Django 3.2 on 2023-04-02 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0006_alter_fileupload_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='uploaded_page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='snippets.snippet'),
            preserve_default=False,
        ),
    ]
