# Generated by Django 3.2 on 2023-04-03 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0007_fileupload_uploaded_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='uploaded_page',
        ),
    ]
