# Generated by Django 3.2 on 2023-01-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('score', models.IntegerField(choices=[(1, '低'), (2, '普通'), (3, '重要'), (4, '最重要'), (5, '緊急')])),
                ('text', models.TextField()),
            ],
        ),
    ]
