# Generated by Django 3.2 on 2022-12-20 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namae', models.CharField(max_length=200)),
                ('old', models.IntegerField(default=0)),
                ('money', models.IntegerField(default=0)),
            ],
        ),
    ]
