# Generated by Django 3.2 on 2023-04-02 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='file/%Y/%m/%d')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='commented_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.snippet', verbose_name='ポイント'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='code',
            field=models.TextField(blank=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='description',
            field=models.TextField(blank=True, verbose_name='参考文献・過去積算案件'),
        ),
    ]
